//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace MathTVZApp.Controls {
    
    
    public partial class PocetniEkran {
        
        /// <summary>
        /// ucImaginarnaJedinicaJednadzba control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::MathTVZApp.Controls.ImaginarnaJedinicaJednadzba ucImaginarnaJedinicaJednadzba;
        
        /// <summary>
        /// ucImaginarnaJedinicaDefinicija control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::MathTVZApp.Controls.DefinicijaImaginarneJedinice.ImaginarnaJedinicaDefinicija ucImaginarnaJedinicaDefinicija;
        
        /// <summary>
        /// btnDalje control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button btnDalje;
        
        /// <summary>
        /// btnNazad control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button btnNazad;
    }
}
